version: "3.9"
services:
    web:
        build: .
        ports:
            - "1433:1433"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Y.14768013"
            ACCEPT_EULA: "Y"